#  Copyright 2017-2020 bmcstdio
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
---
networks:
  main:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.255.0/24
      driver: default
services:
  nats-1:
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
    image: "nats:2.1.4"
    networks:
      - main
    ports:
      - "14222:4222"
      - "18222:8222"
  nats-2:
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
      - "--routes"
      - "nats://nats-1:6222"
    image: "nats:2.1.4"
    networks:
      - main
    ports:
      - "24222:4222"
      - "28222:8222"
  nats-3:
    command:
      - "--debug"
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
      - "--routes"
      - "nats://nats-1:6222"
    image: "nats:2.1.4"
    networks:
      - main
    ports:
      - "34222:4222"
      - "38222:8222"
version: "3.7"
